# This is a basic workflow to help you get started with Actions

name: CI

on:
  status:

jobs:
  automerge-flathubbot-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context))


          
          # if (username == 'flathubbot' && state == 'success')
          #   github.pulls.merge({
          #     pull_number: context.issue.number,
          #     owner: context.repo.owner,
          #     repo: context.repo.repo
          #   })
