# This is a basic workflow to help you get started with Actions

name: CI

on:
  status:

jobs:
  automerge-flathubbot-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            username = github.event.pull_request.user.login
            state = github.event.state
            console.log(username)
            console.log(state)
            if (username == 'flathubbot' && state == 'success')
              github.pulls.merge({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              })
