# This is a basic workflow to help you get started with Actions

name: CI

on:
  status:

jobs:
  automerge-flathubbot-prs:
    if: github.event.pull_request.user.login == 'flathubbot' && github.event.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.pulls.merge({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
