# This is a basic workflow to help you get started with Actions

name: CI

on:
  status:
  workflow_dispatch:

jobs:
  automerge-flathubbot-prs:
    if: github.event.pull_request.user.login == 'flathubbot' && github.event.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
